export const LOAD_TOKEN = "LOAD_TOKEN";
export const DELETE_TOKEN = "DELETE_TOKEN";
export const ERROR = "ERROR";

export const LOAD_PRODUCT_RESULTS = "LOAD_PRODUCT_RESULTS";
export const CLEAR_PRODUCT_RESULTS = "CLEAR_PRODUCT_RESULTS";

export const LOAD_PRODUCT_DETAILS = "LOAD_PRODUCT_DETAILS";

export const LOAD_ALL_STEPS = "LOAD_ALL_STEPS";
export const LOAD_STEP = "LOAD_STEP";
export const ADD_STEP = "ADD_STEP";
export const UPDATE_STEP = "UPDATE_STEP";
export const DELETE_STEP = "DELETE_STEP";
